### ISSUE TITLE
Local CDDD installation has not been found.

### ISSUE THREAD

**Issue by mapengsen** [bayer-science-for-a-better-life/Img2Mol#11]
I want to use local cddd server, and i put the directory default_model to "\\wsl.localhost\Ubuntu-18.04\home\XXX\anaconda3\envs\ldm\lib\python3.8\site-packages\cddd\data" ,but it can't runing :**Local CDDD installation has not been found.**

![image](https://user-images.githubusercontent.com/61998344/205441247-4aa2f91d-8386-4d39-8715-02f37dca79d1.png)

**Comment by mapengsen** [comment]
Consider installing the package zmq to utilize the InferenceServer class
Initializing Img2Mol Model with random weights.
Loading checkpoint: ../model/model.ckpt
Setting to `self.eval()`-mode.
Sending model to `cuda:0` device.
Succesfully created Img2Mol Inference class.
Traceback (most recent call last):
  File "/mnt/d/Pycharm_workspace/molec_recognition/Img2Mol/img2mol/inference.py", line 235, in <module>
    res = img2mol(filepath)
  File "/mnt/d/Pycharm_workspace/molec_recognition/Img2Mol/img2mol/inference.py", line 156, in __call__
    smiles = cddd_server.cddd_to_smiles(cddd.tolist())
AttributeError: 'NoneType' object has no attribute 'cddd_to_smiles'

Process finished with exit code 1
